/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlgv;

import javax.swing.JOptionPane;

/**
 *
 * @author bqd14
 */
public class THAMGIADT extends javax.swing.JFrame {

    DAL_TGDT tgdt = new DAL_TGDT();
    DAL_GIAOVIEN gv = new DAL_GIAOVIEN();
    DAL_CONGVIEC cv = new DAL_CONGVIEC();
    
    public String madtcu, sttcu;
    
    public THAMGIADT() {
        initComponents();
        tbtgdt.setModel(tgdt.Select());
        for(int i = 0; i < gv.Select().getRowCount(); i++){
            cbbmagv.addItem(gv.Select().getValueAt(i, 0).toString());
        }
        for(int i = 0; i < cv.Select().getRowCount(); i++){
            String mdt = cv.Select().getValueAt(i, 0).toString();
            int kt = 0;
            for(int j = 0; j < cbbmadt.getItemCount(); j++){
                if(mdt.equalsIgnoreCase(cbbmadt.getItemAt(j))){
                   kt++;
                } 
            }
            if(kt == 0){
                cbbmadt.addItem(mdt);
            }
            
        }
    }
    public void click(){
        int row = tbtgdt.getSelectedRow();
        String mgv = tbtgdt.getValueAt(row, 0).toString();
        String mdt = tbtgdt.getValueAt(row, 1).toString();
        String stt = tbtgdt.getValueAt(row, 2).toString();
        String phucap = tbtgdt.getValueAt(row, 3).toString();
        String kq = tbtgdt.getValueAt(row, 4).toString();
        cbbmagv.setSelectedItem(mgv);
        cbbmadt.setSelectedItem(mdt);
        cbbstt.addItem(stt);
        cbbstt.setSelectedItem(stt);
        txtphucap.setText(phucap);
        txtkq.setText(kq);
        madtcu = mdt;
        sttcu = stt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbmagv = new javax.swing.JComboBox<>();
        cbbmadt = new javax.swing.JComboBox<>();
        cbbstt = new javax.swing.JComboBox<>();
        txtphucap = new javax.swing.JTextField();
        txtkq = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtgdt = new javax.swing.JTable();
        btxem = new javax.swing.JButton();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        btdong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Giáo Viên");

        jLabel2.setText("Mã Đề Tài");

        jLabel3.setText("Số Thứ Tự");

        jLabel4.setText("Kết Quả");

        jLabel5.setText("Phụ Cấp");

        cbbmadt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmadtActionPerformed(evt);
            }
        });

        cbbstt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbbstt.setToolTipText("");

        tbtgdt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbtgdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtgdtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtgdt);

        btxem.setText("Xem");
        btxem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxemActionPerformed(evt);
            }
        });

        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btxoa.setText("Xoá");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        btdong.setText("Đóng");
        btdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(btxem))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtphucap)
                            .addComponent(txtkq)
                            .addComponent(cbbmagv, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbmadt, 0, 500, Short.MAX_VALUE)
                            .addComponent(cbbstt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btthem)
                        .addGap(80, 80, 80)
                        .addComponent(btsua)
                        .addGap(80, 80, 80)
                        .addComponent(btxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btdong)))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbmagv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbmadt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbstt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtphucap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtkq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btxem)
                    .addComponent(btthem)
                    .addComponent(btsua)
                    .addComponent(btxoa)
                    .addComponent(btdong))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbmadtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmadtActionPerformed
        String madt = cbbmadt.getSelectedItem().toString();
        cbbstt.removeAllItems();
        for(int i = 0; i < cv.Select_stt(madt).getRowCount(); i++){
            cbbstt.addItem(cv.Select_stt(madt).getValueAt(i,0).toString());
        }
    }//GEN-LAST:event_cbbmadtActionPerformed

    private void btxemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxemActionPerformed
        tbtgdt.setModel(tgdt.Select());
    }//GEN-LAST:event_btxemActionPerformed

    private void btdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdongActionPerformed
        this.dispose();
    }//GEN-LAST:event_btdongActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        DAL_TGDT tmp = new DAL_TGDT(cbbmagv.getSelectedItem().toString(), cbbmadt.getSelectedItem().toString(), cbbstt.getSelectedItem().toString(),txtphucap.getText(), txtkq.getText());
        boolean kq = tmp.Insert(tmp);
        if(kq){
            cv.update_tt(cbbmadt.getSelectedItem().toString(), cbbstt.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null,"Insert success");
        }
        else JOptionPane.showMessageDialog(null,"Insert fail");
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
       DAL_TGDT tmp = new DAL_TGDT(cbbmagv.getSelectedItem().toString(), cbbmadt.getSelectedItem().toString(), cbbstt.getSelectedItem().toString(),txtphucap.getText(), txtkq.getText());
       boolean kq = tmp.Update(tmp, madtcu, sttcu);
       if(kq) JOptionPane.showMessageDialog(null,"Update success");
       else  JOptionPane.showMessageDialog(null,"Update fail");
    }//GEN-LAST:event_btsuaActionPerformed

    private void tbtgdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtgdtMouseClicked
       click();
    }//GEN-LAST:event_tbtgdtMouseClicked

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        DAL_TGDT tmp = new DAL_TGDT(cbbmagv.getSelectedItem().toString(), cbbmadt.getSelectedItem().toString(), cbbstt.getSelectedItem().toString(),txtphucap.getText(), txtkq.getText());
       boolean kq = tmp.Delete(tmp);
       if(kq) {
           JOptionPane.showMessageDialog(null,"Delete success");
           cv.rs_tt(cbbmadt.getSelectedItem().toString(), cbbstt.getSelectedItem().toString());
       }
       else  JOptionPane.showMessageDialog(null,"Delete fail");
    }//GEN-LAST:event_btxoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THAMGIADT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THAMGIADT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THAMGIADT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THAMGIADT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THAMGIADT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdong;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btxem;
    private javax.swing.JButton btxoa;
    private javax.swing.JComboBox<String> cbbmadt;
    private javax.swing.JComboBox<String> cbbmagv;
    private javax.swing.JComboBox<String> cbbstt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtgdt;
    private javax.swing.JTextField txtkq;
    private javax.swing.JTextField txtphucap;
    // End of variables declaration//GEN-END:variables
}
